# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      status-page-url-path: /info
      health-check-url-path: /health
      metadata-map:
        app-owner: Jaime Reyes
        description: Servicio Usuario
        initial-status: UP

# Puerto del servidor
server:
  port: 8777

# Configurar Eureka en Ribbon
servicio-item:
  ribbon: 
    listOfServers: http://localhost:8555, http://localhost:8666
    ServerListRefreshInterval: 1000
    eureka:
      enabled: false

# Configuración del datasource (conexión a base de datos)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-usuarios?serverTimezone=UTC
    username: admin
    password: 123456
# Configuración para JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        temp:
          use_jdbc_metadata_defaults: false
#      ddl-auto: update
#    show-sql: true